version: "3.0"
services:
  mysql:
    container_name: blsi-db
    image: mysql:5.7.21
    restart: always
    volumes:
      - 'data/mysql:/var/lib/mysql'
    ports:
      - '3366:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: blsi